# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config/config.yaml"
include: "rules/common.smk"

rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

{% for submodule in cookiecutter.submodules %}
module {{ submodule }}:
    snakefile: "module_workflows/{{ submodule }}/Snakefile"
    prefix: "{{ submodule }}"
    config: config["{{ submodule }}"]
use rule * from {{ submodule }} as {{ submodule }}_*
# some rules in the module are shell commands which call a script assuming the workdir is the other workdir. use symlinks for scripts to fix.
CreateSymlinksOfDir1ContentsIntoDir2("module_workflows/{{ submodule }}/scripts/", "scripts/")
{% endfor %}


include: "rules/other.smk"
